name: Laravel CI

on:
  push:
    branches:
      - main
      - sql-injection
  pull_request:
    branches:
      - main

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, bcmath, gd, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
      
      - name: Run Composer Audit
        run: composer audit

      - name: Run PHPUnit
        run: php artisan test
